
cc_binary(
    name = "demo",
    srcs = [
        "cmdline_parser.cpp",
        "cmdline_parser.h", 
        "main.cpp",
        "profile.h",
        "test_runner.h",
        "unit_tests.cpp",
        "unit_tests.h",
    ],
    deps = [
        "//tld:tld",
    ],
    visibility = ["//demo_app:__pkg__"],
)